# spudtr
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda install conda-build
install:
    - conda build conda -c defaults -c conda-forge
    # - conda create --name spudtr_env spudtr -c file://$HOME/miniconda/conda-bld -c defaults -c conda-forge
    - conda create --name spudtr_env spudtr -c local -c defaults -c conda-forge
    - source activate spudtr_env
    - conda install black pytest-cov
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
    - export TRAVIS_BRANCH  # for deploy script
    - export HOME
    - export TRAVIS
script:
    - black --check --verbose --line-length=79 .
    - pytest --cov=spudtr
after_success:
    - pip install codecov && codecov
before_deploy:
    - pip install sphinx sphinx_rtd_theme jupyter nbsphinx nbconvert!=5.4
    - conda install -c conda-forge pandoc
    - conda install anaconda-client
    - conda list
    - sphinx-apidoc -e -f -o docs/source . ./tests/* ./setup.py
    - make -C docs html
    - touch docs/build/html/.nojekyll
    - chmod +x ./scripts/conda_upload.sh
    - export ANACONDA_TOKEN
deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      on:
          branch: master
      target_branch: gh-pages  # that's the default anyway, just to be explicit
      local_dir: docs/build/html

    - provider: script
      skip_cleanup: true
      script: ./scripts/conda_upload.sh
      on:
          branch: 0.0.0.dev0  # master
