# usage:
#   conda env create -f environment.yml
#   conda activate spudtr
name: spudtr
channels:
    - kutaslab
dependencies:
    - pytest
    - pytest-cov
    - python
    - Cython
    - numpy
    - scipy
    - pandas
    - matplotlib
    - bottleneck
    - pytables
    - pyarrow
