{% set data = load_setup_py_data() %}

package:
  name: spudtr
  version: {{ data.get('version') }}

source:
  # path: ../
  git_url: ../  # to enable GIT_X_Y env vars

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py{{environ.get("CONDA_PY", "XX")}}{{environ.get("GIT_ABBREV_COMMIT", "no_git_abbrev_commit") }}_{{ environ.get("PKG_BUILDNUM", "no_pkg_buildnum") }}

requirements:
  # build ... all moved to host
  host:
    - python {{ python }}
    - pip

  run:
    - python {{ python }}
    - numpy
    - numpy-base
    - scipy
    - pandas >=1.0
    - pyarrow >=1.0
    - matplotlib
    - bottleneck
    - pytables
    - patsy
    - requests
    - mne >=0.20.0

test:
  imports:
    - spudtr

about:
  home: https://github.com/kutaslab/spudtr
  license: BSD
  license_file: LICENSE
