{% set version = "0.0.10.dev0" %}
{% set py_pin = "3.6" %}  # pins for mkpy and fitgrid
{% set np_pin = "1.16.4" %}

package:
    name: spudtr
    version: {{ version }}

source:
    # path: ../
    git_url: ../  # to enable GIT_X_Y env vars

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: {{ environ.get("GIT_ABBREV_COMMIT", "no_git_abbrev_commit") }}_{{ environ.get("PKG_BUILDNUM", "no_pkg_buildnum") }}

requirements:
    # build ... all moved to host
    host:
        - mkl  # should be default on anaconda
        - blas =1.0  # anaconda mkl
        - python ={{ py_pin }}  # else cython uses Python 3.7
        - numpy =={{ np_pin }}
        - numpy-base =={{ np_pin }}
        - Cython

    run:
        - python ={{ py_pin }}
        - numpy =={{ np_pin }}  # these to pull from anaconda for mkl
        - numpy-base =={{ np_pin }}
        - scipy
        - pandas <1.0
        - matplotlib
        - bottleneck
        - pytables
        - pyarrow
        - patsy
        - requests

test:
    imports:
        - spudtr

about:
    home: https://github.com/kutaslab/spudtr
    license: BSD
    license_file: LICENSE
