name: conda-ci
on: [push]
env:
  PACKAGE_NAME: spudtr  # for conda_upload.sh deploy script
  CONDA_BLD_PATH: /usr/share/miniconda/envs/builder/conda-bld
  CONDA_LABEL: "ci-test"  # default conda channel label

defaults:
  run:
    shell:
      bash -l {0}

jobs:
  conda-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_ver: [3.6, 3.7, 3.8]
    env:
      PY_VER: ${{ matrix.py_ver }}

    steps:
      - uses: actions/checkout@v2

      # v0.2.1 or use release tag as above
      - uses: conda-incubator/setup-miniconda@73b9a8098aade40363e43af145303c23542ccb97
        with:
          python-version: ${{ env.PY_VER }}
          activate-environment: builder

      - name: conda build
        run: |
          export GIT_ABBREV_COMMIT=g${GITHUB_SHA:0:8}
          conda config --set always_yes yes --set changeps1 no
          conda install -q conda-build conda-verify
          conda info -a
          conda build --python=$PY_VER -c defaults -c conda-forge conda
          # ls -l -R $CONDA_BLD_PATH/linux-64

      - name: create conda env and install
        run: conda create -n env_$PY_VER python=$PY_VER $PACKAGE_NAME -c file://$CONDA_BLD_PATH -c defaults -c conda-forge

      - name: make sphinx docs
        run: |
          conda install -q sphinx sphinx_rtd_theme jupyter nbsphinx "nbconvert!=5.4" -c defaults -c conda-forge
          conda install -q pandoc
          conda list
          make -C docs html
          touch docs/build/html/.nojekyll
          ls nothing

      - name: black and pytest
        run: |
          conda activate env_$PY_VER
          conda install -q black pytest pytest-cov codecov
          conda list
          lscpu
          python -c 'import numpy; numpy.show_config()'
          black --check --verbose .
          pytest --cov=$PACKAGE_NAME
          codecov

      - name: conda convert and upload packages
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda install -q anaconda
          ls -l -R $CONDA_BLD_PATH/linux-64
          TARBALL=`/bin/ls -1 $CONDA_BLD_PATH/linux-64/${PACKAGE_NAME}-*-*.tar.bz2`
          PKG_VERSION=`echo $TARBALL | sed -n "s/.*${PACKAGE_NAME}-\(.\+\)-.*/\1/p"`
          PKG_MNP=`echo $PKG_VERSION | sed -n "s/\(\([0-9]\+\.\)\{1,2\}[0-9]\+\).*/\1/p"`

          conda convert -p osx-64 -p win-64 $TARBALL -o $CONDA_BLD_PATH
          ls -l -R $CONDA_BLD_PATH/**/${PACKAGE_NAME}*.tar.bz2

          # M.N.P.devX on branch dev uploads to conda label pre-release
          if [[ $GITHUB_REF =~ ^refs/heads/dev$ && $PKG_VERSION =~ ^([0-9]+\.){3}dev[0-9]+$ ]]; then CONDA_LABEL="pre-release"; fi

          # tagged vM.N.P on branch main uploads to conda label main
          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.){2}[0-9]+$ && $PKG_VERSION == $PKG_MNP ]]; then CONDA_LABEL="main"; fi

          # ANACONDA_TOKEN=${ANACONDA_TOKEN:-[not_set]}
          conda_cmd="anaconda --token "$ANACONDA_TOKEN" upload $CONDA_BLD_PATH/**/${PACKAGE_NAME}*.tar.bz2 --label $CONDA_LABEL --skip-existing"
          echo "conda command" $conda_cmd
          # if [[ $CONDA_LABEL == "pre-release" || $CONDA_LABEL == "main" ]]; then $conda_cmd; fi
          $conda_cmd

