name: gh_actionsA
on: [push]
env:
  PACKAGE_NAME: spudtr  # for conda_upload.sh deploy script
  CONDA_BLD: file:///usr/share/miniconda/envs/builder/conda-bld

defaults:
  run:
    shell:
      bash -l {0}

jobs:
  conda-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_M: [3]  # major
        py_N: [6, 7, 8]  # minor
    env:
      # conda builder want python version M.N with the decimal
      # conda tarball package naming convention is pyMN
      PYTHON_M_N: format("{0}.{1}", ${{ matrix.py_M }}, ${{ matrix.py_N }})
      PYMN: format("py{0}{1}", ${{ matrix.py_M }}, ${{ matrix.py_N }})
    steps:
      - uses: actions/checkout@v2
      # vM or SHA for security, v2.0.1 73b9a8098aade40363e43af145303c23542ccb97
      - uses: conda-incubator/setup-miniconda@73b9a8098aade40363e43af145303c23542ccb97
        with:
          python-version: $PYTHON_M_N
          activate-environment: builder

      - name: conda setup
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install -q conda-build conda-verify

      - name: show context info
        run: |
          echo "github_ref" $GITHUB_REF
          conda info -a
          printenv | sort

      - name: conda build
        run: |
          conda build --python=$PYTHON_M_N -c defaults -c conda-forge conda

      - name: conda create env and install
        run: conda create -n env_$PYMN python=$PYTHON_M_N $PACKAGE_NAME -c $CONDA_BLD -c defaults -c conda-forge

      - name: black and pytest
        run: |
          conda activate env_$PYMN
          conda install -q black pytest pytest-cov
          conda list
          lscpu
          python -c 'import numpy; numpy.show_config()'
          # black --check --verbose .
          # pytest --cov=$PACKAGE_NAME

      - name: conda convert and upload
        run: |
          ls -l -R $CONDA_BLD/linux-64/$PACKAGE_NAME-*-$PYMN*.tar.bz2

  # deploy:
  #   needs: package-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: codecov
  #       run: |
  #         printenv | sort
  #         conda env list
  #         conda list
  #         ls -R $CONDA_BLD
