name: gh_actionsA
on: [push]
env:
  PACKAGE_NAME: spudtr  # for conda_upload.sh deploy script
  CONDA_BLD_PATH: /usr/share/miniconda/envs/builder/conda-bld
  CONDA_LABEL: "dry-run"  # default

defaults:
  run:
    shell:
      bash -l {0}

jobs:
  conda-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_M: [3]  # major
        py_N: [6, 7, 8]  # minor
        # for testing only 
        # fake_github_ref: ["refs/heads/dev", "refs/heads/not_dev", "refs/tags/v0.0.0"]
    env:
      # conda builder want python version M.N with the decimal
      # conda tarball package naming convention is pyMN
      PYTHON_M_N: ${{ format('{0}.{1}', matrix.py_M , matrix.py_N) }}
      PYMN: ${{ format('py{0}{1}', matrix.py_M, matrix.py_N) }}
      # for testing only 
      # FAKE_GITHUB_REF: ${{ matrix.fake_github_ref }}

    outputs:
      git_ssha: ${{ steps.get_ssha.outputs.ssha }}

    steps:

      - id: get-ssha
        run: echo "::set-output name=ssha::(g${GITHUB_SHA:0:8})"

      - name: env dump
        run: printenv | sort

      # - uses: actions/checkout@v2

      # use @vM or @SHA for security, this is v2.0.1
      # - uses: conda-incubator/setup-miniconda@73b9a8098aade40363e43af145303c23542ccb97
      #   with:
      #     python-version: ${{ env.PYTHON_M_N }}
      #     activate-environment: builder

      - name: conda build
        run: |
          export GIT_ABBREV_COMMIT=g$(git log --full-history --abbrev-commit --oneline -n 1 | awk '{print $1}')
          # conda config --set always_yes yes --set changeps1 no
          # conda install -q conda-build conda-verify
          # conda info -a
          # conda build --python=$PYTHON_M_N -c defaults -c conda-forge conda
          # for testing 
          mkdir -p $CONDA_BLD_PATH/linux-64
          #touch $CONDA_BLD_PATH/linux-64/$PACKAGE_NAME-0.0.0.dev0-${PYMN}_dummy.tar.bz2
          touch $CONDA_BLD_PATH/linux-64/$PACKAGE_NAME-0.0.0-${PYMN}_dummy.tar.bz2
          ls -l -R $CONDA_BLD_PATH/linux-64

      # - name: conda create env and install
      #   run: conda create -n env_$PYMN python=$PYTHON_M_N $PACKAGE_NAME -c file://$CONDA_BLD_PATH -c defaults -c conda-forge

      # - name: pytest 
      #   run: |
      #     conda activate env_$PYMN
      #     conda install -q black pytest pytest-cov
      #     conda list
      #     lscpu
      #     python -c 'import numpy; numpy.show_config()'
      #     # black --check --verbose .
      #     # pytest --cov=$PACKAGE_NAME

      - name: conda convert 
        run: |
          ls -l -R $CONDA_BLD_PATH/linux-64/$PACKAGE_NAME-*-$PYMN*.tar.bz2
          # conda convert -p osx-64 -p win-64 /tmp/$PYMN/linux-64/*.tar.bz -o /tmp/$PYMN

      - name: conda upload
        run: |
          TARBALL=`/bin/ls -1 $CONDA_BLD_PATH/linux-64/${PACKAGE_NAME}-*-*.tar.bz2`
          PKG_VERSION=`echo $TARBALL | sed -n "s/.*${PACKAGE_NAME}-\(.\+\)-.*/\1/p"`
          PKG_MNP=`echo $PKG_VERSION | sed -n "s/\(\([0-9]\+\.\)\{1,2\}[0-9]\+\).*/\1/p"`

          # M.N.P.devX on branch dev upload to conda label pre-release
          if [[ $GITHUB_REF =~ ^refs/heads/dev$ && $PKG_VERSION =~ ^([0-9]+\.){3}dev[0-9]+$ ]]; then CONDA_LABEL="pre-release"; fi

          # tagged vM.N.P on branch main upload to conda label main
          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.){2}[0-9]+$ && $PKG_VERSION == $PKG_MNP ]]; then CONDA_LABEL="main"; fi
          export CONDA_LABEL TARBALL PKG_VERSION PKG_MNP
          printenv | sort

          # ANACONDA_TOKEN=${ANACONDA_TOKEN:-[not_set]}
          conda_cmd="anaconda --token $ANACONDA_TOKEN upload $CONDA_BLD_PATH/**/${PACKAGE_NAME}*.tar.bz2 --label $CONDA_LABEL --skip-existing"
          echo "conda command" $conda_cmd


